version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:alpine-3.6_ocaml-4.04.2
        environment:
          TERM: xterm
    steps:
      - run:
          name: Update opam
          command: |
            opam remote remove default
            opam remote add default https://opam.ocaml.org
      - checkout
      - run:
          name: Pin packages
          command: |
            opam pin add -y -n easy_xlsx .
            opam pin add -y -n open_packaging .
            opam pin add -y -n spreadsheetml .
      - run:
          name: Install system dependencies
          command: opam depext -y easy_xlsx open_packaging spreadsheetml
      - run:
          name: Install OCaml dependencies
          command: opam install --deps-only -y easy_xlsx open_packaging spreadsheetml
      - run:
          name: Build
          command: opam config exec -- make
      - run:
          name: Install OCaml test dependencies
          # Not using opam install -y -t because it tries to run csv's tests
          command: opam install -y csv oUnit
      - run:
          name: Test
          command: opam config exec -- make test
      - run:
          name: Coverage
          command: opam config exec -- make coverage
      - run:
          name: Install ocveralls
          command: opam install -y ocveralls
      - run:
          name: Upload coverage report
          command: |
            cd _build/default
            shopt -s globstar
            opam config exec -- ocveralls **/bisect*.out --send --repo_token $COVERALLS_REPO_TOKEN --git
